### ISSUE TITLE
Improved view for the visualizer module

### ISSUE THREAD

**Issue by drexpp** [EGC-Decide/locaste#18]
Start date: 04/12/2018

Description: We will provide a new view for the visualizer module in order to do so, we are going to use a javascript library to graphically show the results of votings. 

- [x] Find a suitable js library to use
- [x] Implement the library so it can be used with actual view and votings results
- [x] Improve the overall view style
- [x] Merge changes to locaste (dev branch)
- [x] Merge changes to locaste (master branch)

**Comment by jesusrico12** [comment]
We decided to use the Chart.js library because it has many types of very friendly designs.

**Comment by jesusrico12** [comment]
Implementation of chart.js,responsive web design and improved data visualization.

**Comment by jesusrico12** [comment]
@MrMJ06 Hello, since visualization we use the voting url (voting/id?=) to get information about a vote. We would like to know if it is possible, in order to integrate changes of your subsystem with ours, that appears some "new" information about for example, amount of the census that has voted (20%, 33.5%,...) or for example the type of count used in the postprocessing ('IDENTITY', 'HONT',...).

If you have any better idea, I would appreciate your comment.

**Comment by MrMJ06** [comment]
> 
> 
> @MrMJ06 Hello, since visualization we use the voting url (voting/id?=) to get information about a vote. We would like to know if it is possible, in order to integrate changes of your subsystem with ours, that appears some "new" information about for example, amount of the census that has voted (20%, 33.5%,...) or for example the type of count used in the postprocessing ('IDENTITY', 'HONT',...).
> 
> If you have any better idea, I would appreciate your comment.

@jesusrico12 Hi, actually that information is only available for postproc subsystem. I think that the easiest way to access to that information is to change the JSON representation retrieving the information that you need (which is not difficult to do). In that case, you can make a new issue with all the fields you would like to appear in the JSON that will be closed as soon as possible.  If you can give an JSON example it will be appreciated.

**Comment by angbongon** [comment]
> > @MrMJ06 Hello, since visualization we use the voting url (voting/id?=) to get information about a vote. We would like to know if it is possible, in order to integrate changes of your subsystem with ours, that appears some "new" information about for example, amount of the census that has voted (20%, 33.5%,...) or for example the type of count used in the postprocessing ('IDENTITY', 'HONT',...).
> > If you have any better idea, I would appreciate your comment.
> 
> @jesusrico12 Hi, actually that information is only available for postproc subsystem. I think that the easiest way to access to that information is to change the JSON representation retrieving the information that you need (which is not difficult to do). In that case, you can make a new issue with all the fields you would like to appear in the JSON that will be closed as soon as possible. If you can give an JSON example it will be appreciated.

@jesusrico12 this in fact true, currently you are able to obtain participation percentages accessing the field participation. Here you have an example: 
`{
            'results': [
                { 'option': 'Option 1', 'number': 1, 'votes': 5, 'postproc': 5 },
                { 'option': 'Option 5', 'number': 5, 'votes': 5, 'postproc': 5 },
                { 'option': 'Option 3', 'number': 3, 'votes': 3, 'postproc': 3 },
                { 'option': 'Option 4', 'number': 4, 'votes': 2, 'postproc': 2 },
                { 'option': 'Option 6', 'number': 6, 'votes': 1, 'postproc': 1 },
                { 'option': 'Option 2', 'number': 2, 'votes': 0, 'postproc': 0 },
            ],
            'participation': 69.57,
        }`
