### ISSUE TITLE
Create interface into voting subsystem

### ISSUE THREAD

**Issue by MrMJ06** [EGC-Decide/locaste#44]
Create a interface for easiest customization of all voting subsystem. This must include:

- [x]  Voting/Question list
- [x]  Voting/Question Creation/Modification/Delete form

**Comment by lujalolo** [comment]
interface fixed errorr and funtional  implementation completed 
 in commit : 3ba8805

**Comment by MrMJ06** [comment]
The modification and deletion of voting will be available only in the admin view due to his importance.
