### ISSUE TITLE
Obtain participation percentages

### ISSUE THREAD

**Issue by angbongon** [EGC-Decide/locaste#45]

**Comment by angbongon** [comment]
It would be needed to add to the json file that Voting and Postproc subsystems share, a field that specifies the census size for that particular voting.

**Comment by jualinfer** [comment]
You can get the list of users that are part of the census of a voting from the census API already, so you only need to get its size. To get this list, do a GET petition to "_.../census/?voting_id=**X**_", where _**X**_ is the ID number of the voting you are looking for.

**Comment by angbongon** [comment]
Closed with commit c823b68
