### ISSUE TITLE
Add voting retrieve API call

### ISSUE THREAD

**Issue by MrMJ06** [EGC-Decide/locaste#58]
Voting subsystem must add a API GET method which receive the id of an voting and will retrieve a voting in JSON format.

Call example:
voting/getVoting/?id=<voting_id>

**Comment by AlexGue** [comment]
Studied and concluded is not necessary because DJANGO already has a API for the models.
Example for voting items.
http://127.0.0.1:8000/voting/?format=json&id=2
This will return the object in plain text with json formact as requested.
