### ISSUE TITLE
request.user not working when logged in

### ISSUE THREAD

**Issue by carjimcor** [EGC-Decide/locaste#63]
Description: in any 'views.py' method, when you try to get the loged user by calling 'request.user', it always return anonymous user even when you are logged in. 

I've tried it with the methods in census/views.py, using the debug mode of pycharm, to check what attributes does 'request' have. I guess it must be happening too in the other submodules.

**Comment by iNSDX** [comment]
I've taken a look on it and I am able to retrieve the authenticated user. I've talked with @carjimcor and @EGC-Decide/locaste-censo it's going to take a deeper look into it
