### ISSUE TITLE
Range votings

### ISSUE THREAD

**Issue by lujalolo** [EGC-Decide/locaste#7]
Start date: 28/11/2018

Description:
This issue is an increase in which a type of voting will be implemented in which users can choose an option in a range.
This issue will be divided into subtasks such as: modeling, logic and visualization.

**Comment by angbongon** [comment]
Please, when possible specify the JSON format in order to integrate the enhancement in postproc subsystem.

**Comment by lujalolo** [comment]
Implemented  in commit : 3ba8805a49543fada367896f6d17fd3d8a31b66e
